version: '3'

services:
  searchservice:
    build:
      context: .
      dockerfile: ./SearchService/Dockerfile
    ports:
      - "8081:8080"

  productservice:
    build:
      context: .
      dockerfile: ./ProductService/Dockerfile
    ports:
      - "8082:8080"


  userservice:
    build:
      context: .
      dockerfile: ./UserService/Dockerfile
    ports:
      - "8083:8080"

  some-rabbit:
    image: masstransit/rabbitmq:latest
    hostname: my-rabbit
    container_name: some-rabbit
    ports:
      - "15672:15672"
      - "5672:5672"